training:
  epochs: 10
  lr: 1e-3
  batch_size: 128
  dataset: mnist
  seed: null
eval:
  datasets: [mnist, svhn]
hardware:
  gpus: 0
  num_workers: 6
paths:
  project: ${hydra:runtime.cwd}
  data: ${hydra:runtime.cwd}/data/
  model: models/
  logs: logs/
  checkpoints: models/checkpoints/
files:
  train: train.csv
  test: test.csv
  state_dict: state_dict.pt
