params:
  epochs: 3
  lr: 5e-3
  batch_size: 1024
hardware:
  gpus: 0
  num_workers: 16
paths:
  project: ${hydra:runtime.cwd}
  data: ${hydra:runtime.cwd}/data/processed/
  checkpoints: models/checkpoints/weights/
  model: models/
  logs: logs/
files:
  train: train.csv
  test: test.csv
  state_dict: state_dict.pt
