params:
  epochs: 1
  lr: 1e-2
  batch_size: 8192
  num_particles: 32
  posterior_samples: 128
  guide: meanfield
hardware:
  gpus: 0
  num_workers: 16
paths:
  project: ${hydra:runtime.cwd}
  data: ${hydra:runtime.cwd}/data/
  checkpoints: models/checkpoints/weights/
  model: models/
  logs: logs/
files:
  train: train.csv
  test: test.csv
  state_dict: state_dict.pt
  pretrained_weights: null
